# path to hardware watchdog
watchdog-device = /dev/watchdog
# Hardware timeout before reset if not refreshed (14 or 15 recommended on Pi)
watchdog-timeout = 15
# How often the daemon wakes up, checks conditions, and refreshes the watchdog
interval = 5
# Lock watchdog into real-time scheduling so it is less likely to be starved
realtime = yes
# Scheduling priority used with real-time mode
priority = 1
# Path to heartbeat
# file = /tmp/heartbeat
# Time threshold for reboot trigger if heartbeat has not been updated
# change = 60